apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/fabiocruzcoelho/argocd-vault-plugin.git
    targetRevision: HEAD
    path: .
    helm:
      repoURL: https://charts.visonneau.fr/
      chart: "generic-app"
      chartVersion: "0.0.11"
      valueFiles: 
      - values.yml
      - values-dit.yaml

