---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-demo-app-dev
  namespace: argocd
  labels:
    app: demo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: nodejs-demo-app
    server: https://0ECADEEC939AA89AC2CDCF742B33571B.gr7.us-east-1.eks.amazonaws.com
  project: nodejs-demo-app
  source:
    path: .
    repoURL: https://github.com/fabiocruzcoelho/argocd-vault-plugin.git
    targetRevision: main
    # helm specific config
    helm:
      parameters:
      # Release name override (defaults to application name)
      releaseName: demo
      # Helm values files for overriding values in the helm chart
      # The path is relative to the spec.source.path directory defined above
      valueFiles:
        - values.yaml
        - values-default.yaml
        - values-dev.yaml
      # Values file as block file
      values: |
        generic-app:
          nameOverride: demo
          ingress:
            enabled: false
            hosts:
              - nodejs-demo-app.dev.
            tls:
              - secretName: wildcard-crt
                hosts:
                  - nodejs-demo-app.dev.
          pods:
            replicas: 1
            image:
              name: registry.gitlab.vitta.tools/devops/nodejs-demo-app/nodejs-demo-app
              tag: develop
              pullPolicy: Always
              pullCredentials:
                registry: registry.gitlab.vitta.tools
                username: argocd-deploy
                password: vMyd_uc-iGYxzqybTbWy

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true