apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-dit
spec:
  project: default
  source:
    repoURL: https://github.com/fabiocruzcoelho/argocd-vault-plugin.git
    targetRevision: HEAD
    path: ""
    helm:
      repoURL: https://charts.visonneau.fr/
      chart: "generic-app"
      chartVersion: "0.0.11"
      valueFiles: ['values-dit.yaml'] # resolved against source.repoURL and source.path
