---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/fabiocruzcoelho/argocd-vault-plugin.git
    targetRevision: HEAD
    path: .
    helm:
    #   # repoURL: https://charts.visonneau.fr/
    #   # chart: "generic-app"
    #   # chartVersion: "0.0.11"
    #   # helm specific config
      parameters:

    #   # Release name override (defaults to application name)
      releaseName: demo

      valueFiles: 
      - values-default.yaml
      - values-dev.yaml
      
      values: |
        generic-app:
          nameOverride: demo
