apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-application-example
spec:
  destination:
    name: in-cluster
    namespace: default
  project: example
  source:
    path: .
    repoURL: https://github.com/fabiocruzcoelho/argocd-vault-plugin.git
  syncPolicy:
    automated:
      selfHeal: true
