apiVersion: v1
kind: Secret
metadata:
  name: auth
  annotations:
    avp.kubernetes.io/path: "avp/data/example/example-auth"
type: Opaque
stringData:
  username: <username>
  password: <password>
  dbpass: <dbpass>
