---
generic-app:
  nameOverride: ${ARGOCD_POD_NAME}

  pods:
  # pods.controller -- controller used to schedule pods
  # Can either be 'deployment', 'statefulset' or 'daemonset'
  controller: deployment

  # Container image to use
  image:
    # pods.image.name -- image repository/name
    name: ${CI_REGISTRY_IMAGE}/${CI_PROJECT_NAME}

    # pods.image.tag -- image tag
    tag: ${CI_COMMIT_REF_NAME}

    # pods.image.pullPolicy -- image pullPolicy
    pullPolicy: Always

    ingress:
    enabled: ${KUBE_INGRESS_ENABLED}
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      certmanager.k8s.io/cluster-issuer: letsencrypt-prod
      certmanager.k8s.io/acme-challenge-type: dns01
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"

    path: /
    pathType: Prefix

    service:
      port:
        name: http

    hosts: 
      - ${CI_PROJECT_NAME}.${KUBE_INGRESS_BASE_DOMAIN}
    tls:
      - hosts:
          - ${CI_PROJECT_NAME}.${KUBE_INGRESS_BASE_DOMAIN}
        secretName: wildcard-crt
